# Generated by Django 2.2.10 on 2021-05-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('data', models.IntegerField(verbose_name='Data')),
                ('numero_da_dose', models.IntegerField(verbose_name='Número da dose')),
            ],
        ),
    ]
